# A03-PYTHON 

Terezza Marianne González Jáuregui

26/08/2024

1. Toma el archivo datosCT.xlsx y

   
*  
calcula la Utilidad (Ingreso - Gasto)
* encuentra el promedio de Gastos en los meses que la Utilidad fue negativa
* encuentra los ingresos totales del  año

In [30]:
import pandas as pd
datos = pd.read_excel("datosCT.xlsx")#Llamar un archivo
datos

Unnamed: 0  Ingreso  Gasto
0        Enero     1340   1880
1      Febrero     2590   3130
2        Marzo     3570   2140
3        Abril     4450   3370
4         Mayo     1330   2990
5        Junio     1610   1970
6        Julio     1500   2230
7       Agosto     2270   1240
8   Septiembre     1910   1470
9      Octubre     2120   2280
10   Noviembre     3950   1870
11   Diciembre     1380   3140

In [40]:
datos["Utilidad"]=datos["Ingreso"]-datos["Gasto"] #Agregas una columna
datos

Unnamed: 0  Ingreso  Gasto  Utilidad
0        Enero     1340   1880      -540
1      Febrero     2590   3130      -540
2        Marzo     3570   2140      1430
3        Abril     4450   3370      1080
4         Mayo     1330   2990     -1660
5        Junio     1610   1970      -360
6        Julio     1500   2230      -730
7       Agosto     2270   1240      1030
8   Septiembre     1910   1470       440
9      Octubre     2120   2280      -160
10   Noviembre     3950   1870      2080
11   Diciembre     1380   3140     -1760

In [55]:
Promedio_Gastos_Filtro=datos[ datos["Utilidad"]<0]["Gasto"] #Filtrar 
Promedio_Gastos= Promedio_Gastos_Filtro.mean() #.mean para sacar el promedio
Promedio_Gastos

2517.1428571428573

In [57]:
Ingreso_totales=datos["Ingreso"].sum()
Ingreso_totales

28020

2. Crea las siguientes estructuras usando numpy:

 * Encuentra el resultado de Ab

In [66]:
import numpy as np
A= np.array([
    [1,2],
    [3,4]
])
A

array([[1, 2],
       [3, 4]])

In [68]:
b= np.array([
    [2],
    [4]
])
b

array([[2],
       [4]])

In [74]:
A @ b #da una matriz de 2x1

array([[10],
       [22]])