## Programación lineal

Terezza Marianne González Jauregui

09/09/2024

**Ejercicio 1.**

Una carpintería local fabrica sillas, mesas, libreros y bases de cama. Hay dos empleados en esta carpintería: un empleado experimentado y un aprendiz. El aprendiz tarda aproximadamente 50% más tiempo que el carpintero experimentado en construir cualquier cosa, además de que tiene un desperdicio de alrededor de 20% de material. Los materiales y tiempos necesarios para construir algo se desglozan en la siguiente tabla:

Las mesas se venden en $9000, las sillas en $3000, los libreros en $10000, y las bases de cama en $9000. Suponiendo una jornada de 40 horas a la semana y que tienen 100 unidades de madera.ado?

1. Identificar criterio
   * Maximizar las ganancias de la semana
     
2. Variables de control
   * Cantidad de sillas que hace el experimentado (se)
   * Cantidad de mesas que hace el experimentado (me)
   * Cantidad de libreros que hace el experimentado (le)
   * Cantidad de bases que hace el experimentado (be)
   * Cantidad de sillas que hace el aprendiz (sa)
   * Cantidad de mesas que hace el aprendiz (ma)
   * Cantidad de libreros que hace el aprendiz (la)
   * Cantidad de bases que hace el aprendiz (ba)
     
3. Función de costo
   * Costo(se,me,le,be,sa,ma,la,ba)= 9000me+9000ma+3000se+3000sa+10000le+10000la+9000be+9000ba
     
4. Información adicional (restricciones)
   
   * Tiempo $\leq$ 40 cada quien
   
 3me+1se+4le+3be $\leq$ 40

 4.5ma+1.5sa+6la+4.5ba $\leq$ 40

* Material $\leq$ 100

6me+7.2ma+2se+2.4sa+5le+6la+5be+6ba $\leq$ 100

$$ \min_{me,ma,se,sa,le,la,be,ba} -9000me-9000ma-3000se-3000sa-10000le-10000la-9000be-9000ba $$
$$ \text {s.t.} $$
$$3me+1se+4le+3be \leq 40$$
$$4.5ma+1.5sa+6la+4.5ba \leq 40$$
$$6me+7.2ma+2se+2.4sa+5le+6la+5be+6ba \leq 100$$

In [119]:
import numpy as np
import scipy.optimize as opt

c=np.array([
    -9000,
    -9000,
    -3000,
    -3000,
    -10000,
    -10000,
    -9000,
    -9000
])

Aub=np.array([
    [   3,   0,   1,   0,   4,   0,   3,   0],
    [   0, 4.5,   0, 1.5,   0,   6,   0, 4.5],
    [   6, 7.2,   2, 2.4,   5,   6,   5,   6]
])

bub=np.array([
    40,
    40,
    100
])

sol= opt.linprog(c,Aub,bub,integrality=1) # Este comando ya da la respuesta para la forma vector
sol

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: -176000.0
              x: [ 0.000e+00  0.000e+00  1.000e+00 -9.474e-15  9.000e+00
                   2.000e+00  1.000e+00  6.000e+00]
            nit: -1
          lower:  residual: [ 0.000e+00  0.000e+00  1.000e+00 -9.474e-15
                              9.000e+00  2.000e+00  1.000e+00  6.000e+00]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00  0.000e+00  0.000e+00]
          upper:  residual: [       inf        inf        inf        inf
                                    inf        inf        inf        inf]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00  0.000e+00  0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 0.000e+00  1.000e+00  0.00

* ¿qué les conviene construir durante una semana para maximizar su ganancia?

In [64]:
sol.x
# Les conviene:
    #Experto: 0 mesas, 1 silla, 9 libreros y 1 base
    #Aprendiz: 0 mesas, o sillas, 2 libreros y 6 bases

array([ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00, -9.47390314e-15,
        9.00000000e+00,  2.00000000e+00,  1.00000000e+00,  6.00000000e+00])

* ¿Cuántas horas trabaja cada quién?
* 
¿Cuánto material se usa?

In [39]:
Aub@sol.x
# El experto trabaja 40 horas
# El aprendiz trabaja 39
# Se ocupó 100 de material

array([ 40.,  39., 100.])

* ¿Cuál se el ingreso total si se vende todo lo fabricado?

In [121]:
sol.fun
# Se vende 176000

-176000.0

2. La carpintería recibió una orden por 3 combos de mesa + 6 sillas.

* ¿Se puede cumplir la orden?
* Si sí, ¿qué es lo que tienen que fabricar en el resto del tiempo y con el resto del material para maximizar su ganancia?
* ¿Cuántas horas trabaja cada quién?
* ¿Cuánto material se usa?
* ¿Cuál es el nuevo ingreso total?

1. Identificar criterio
   * Maximizar las ganancias de la semana y cumplir con los combos.
     
2. Variables de control
   * Cantidad de sillas que hace el experimentado (se)
   * Cantidad de mesas que hace el experimentado (me)
   * Cantidad de libreros que hace el experimentado (le)
   * Cantidad de bases que hace el experimentado (be)
   * Cantidad de sillas que hace el aprendiz (sa)
   * Cantidad de mesas que hace el aprendiz (ma)
   * Cantidad de libreros que hace el aprendiz (la)
   * Cantidad de bases que hace el aprendiz (ba)
     
3. Función de costo
   * Costo(se,me,le,be,sa,ma,la,ba)= 9000me+9000ma+3000se+3000sa+10000le+10000la+9000be+9000ba
     
4. Información adicional (restricciones)

 Sillas:
 se+sa $\geq$ 18

 Mesas:
 me+ma $\geq$ 3
   
   * Tiempo $\leq$ 40 cada quien
   
 3me+1se+4le+3be $\leq$ 40

 4.5ma+1.5sa+6la+4.5ba $\leq$ 40

* Material $\leq$ 100

6me+7.2ma+2se+2.4sa+5le+6la+5be+6ba $\leq$ 100


$$ \min_{me,ma,se,sa,le,la,be,ba} -9000me-9000ma-3000se-3000sa-10000le-10000la-9000be-9000ba $$
$$ \text {s.t.} $$
$$3me+1se+4le+3be \leq 40$$
$$4.5ma+1.5sa+6la+4.5ba \leq 40$$
$$6me+7.2ma+2se+2.4sa+5le+6la+5be+6ba \leq 100$$
$$ se+sa \geq 18 $$
$$ me+ma \geq 3 $$

In [134]:
import numpy as np
import scipy.optimize as opt

c=np.array([
    -9000,
    -9000,
    -3000,
    -3000,
    -10000,
    -10000,
    -9000,
    -9000
])

Aub=np.array([
    [   3,   0,   1,   0,   4,   0,   3,   0],
    [   0, 4.5,   0, 1.5,   0,   6,   0, 4.5],
    [   6, 7.2,   2, 2.4,   5,   6,   5,   6],
    [   0,   0,  -1,  -1,   0,   0,   0,   0],
    [  -1,  -1,   0,   0,   0,   0,   0,   0],
])

bub=np.array([
      40,
      40,
     100,
     -18,
      -3
])

sol2= opt.linprog(c,Aub,bub,integrality=1) # Este comando ya da la respuesta para la forma vector
sol2

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: -161000.0
              x: [ 3.000e+00  0.000e+00  1.800e+01  0.000e+00  3.000e+00
                   5.000e+00  0.000e+00  0.000e+00]
            nit: -1
          lower:  residual: [ 3.000e+00  0.000e+00  1.800e+01  0.000e+00
                              3.000e+00  5.000e+00  0.000e+00  0.000e+00]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00  0.000e+00  0.000e+00]
          upper:  residual: [       inf        inf        inf        inf
                                    inf        inf        inf        inf]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00  0.000e+00  0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 1.000e+00  1.000e+01  1.00

* ¿Se puede cumplir la orden?

In [ ]:
Si se puede

* Si sí, ¿qué es lo que tienen que fabricar en el resto del tiempo y con el resto del material para maximizar su ganancia?

In [147]:
sol2.x
# Les conviene:
    #Experto: 3 mesas, 18 silla, 3 libreros y 0 base
    #Aprendiz: 0 mesas, 0 sillas, 5 libreros y 0 bases

array([ 3.,  0., 18.,  0.,  3.,  5.,  0.,  0.])

* ¿Cuántas horas trabaja cada quién?
* ¿Cuánto material se usa?

In [145]:
Aub@sol2.x
# El experto trabaja 39 horas
# El aprendiz trabaja 30
# Se ocupó 99 de material

array([ 39.,  30.,  99., -18.,  -3.])

* ¿Cuál es el nuevo ingreso total?

In [142]:
sol2.fun
# Se vende 161000

-161000.0