# T04_Programación lineal

Terezza Marianne González Jáuregui

16/09/2024

### 02 Programación lineal.ipynb

**2.1. Ejemplo básico**

Una multinacional farmacéutica desea fabricar un compuesto nutritivo a base de dos productos A y B.  El producto A contiene  $30\%$ de proteínas,  un $1\%$ de grasas y un  $10\%$ de azúcares.  El producto B  contiene  un  $5\%$  de proteínas,  un  $7\%$ de grasas  y un  $10\%$  de  azúcares.

El compuesto debe de tener,  al menos, $25g$ de proteínas,  $6g$ de grasas y $30g$ de azúcares.  El coste del producto A es de $0.6$ u.m./g  y el de B es de $0.2$  u.m./g

Se desea encontrar la cantidad en gramos de cada producto para que el coste total sea mínimo.

Formular el problema de decidir cuánto hacer de cada producto como un problema de programación lineal.

1. Identificar criterio
   * Minimizar gastos
2. Variables de control
   * Cantidad de producto A (Xa)
   * Cantidad de producto B(Xb)

3. Función de costo
   * Costo(Xa,Xb)=0.6Xa+0.2Xb
4. Información adicional (restricciones)
   * Proteinas ≥ 25g
   * Grasas ≥ 6g
   * Azucares ≥ 30g
* prot= 0.3Xa + 0.005Xb ≥ 25
* Gras= 0.01Xa + 0.07Xb ≥ 6
* Azuc= 0.10Xa + 0.10Xb ≥ 30

$$ \min_{Xa,Xb} 0.6Xa+0.2Xb $$
$$ \text {s.t.} $$
$$ 0.30Xa + 0.05Xb \geq 25 $$
$$ 0.0.1Xa + 0.07Xb \geq 6 $$
$$ 0.10Xa + 0.10Xb \geq 30 $$

In [145]:
import numpy as np
import scipy.optimize as opt

c=np.array([0.6,0.2])

Aub=np.array([
    [-0.30,-0.05],
    [-0.01,-0.07],
    [-0.10,-0.10]
])

bub=np.array([-25,-6,-30])

sol= opt.linprog(c,Aub,bub) # Este comando ya da la respuesta para la forma vector
sol.fun

76.0

In [147]:
sol.x

array([ 40., 260.])

In [149]:
Aub@sol.x

array([-25. , -18.6, -30. ])

**2.2. Ejemplo básico 2**
Una  fábrica  de  carrocerías  de  automóviles  y camiones  tiene  dos naves. 

+ En  la nave A,  para  hacer  la  carrocería  de  un  camión,  se  invierten  siete  días-operario,  para  fabricar  la  de  un  coche  se  precisan dos días-operario.

+ En la nave B se invierten tres días operario tanto en carrocerías de camión como de coche. 

Por limitaciones de mano de obra y maquinaria, la nave A dispone de $300$ días operario, y la nave B de $270$ días-operario.

Si los beneficios que se obtienen por cada camión son de $600$ u.m y por  cada  automóvil  $200$ u.m,  ¿cuántas  unidades  de  cada  uno  se deben  producir  para maximizar las  ganancias? 

**Nota:** el problema $\max_{\boldsymbol{x}}\boldsymbol{g}(\boldsymbol{x})$ es equivalente a $\min_{\boldsymbol{x}}-\boldsymbol{g}(\boldsymbol{x})$.

1. Identificar criterio
   * Maximizar las ganacias de logísticas. 
2. Variables de control
   * Cantidad de Autos en la nave A (Aa)
   * Cantidad de Autos en la nave B (Ab)
   * Cantidad de Camiones en la nave A (Ca)
   * Cantidad de Camiones en la nave B (Cb)

3. Función de costo
   * Costo(Aa,Ca, Ab, Cb)= 200Aa+600Ca+200Ab+600Cb
4. Información adicional (restricciones)
   * Nave A = 300 dias
   * Nave B = 270 dias

   * A se tarda 7 dias por coche y 2 por auto
   * B se tarda 3 dias poc covhe y 3 por auto
  
   * Nave A: 2Aa+7Ca≤300
   * Nave B: 3Ab+3Cb ≤ 270

$$ \min_{Aa,Ca, Ab, Cb} -200Aa-600Ca-200Ab-600Cb $$
$$ \text {s.t.} $$
$$ 2Aa+7Ca≤300 $$
$$ 3Ab+3Cb ≤ 270 $$

In [151]:
import numpy as np
import scipy.optimize as opt

c=np.array([
    -200,
    -600,
    -200,
    -600
])

Aub=np.array([
    [ 2, 7, 0, 0],
    [ 0, 0, 3, 3]
])

bub=np.array([
    300,
    270
])

sol2= opt.linprog(c,Aub,bub,integrality=1) # Este comando ya da la respuesta para la forma vector
sol2.fun

-84000.0

In [153]:
sol2.x

array([150.,  -0.,   0.,  90.])

In [155]:
Aub@sol2.x

array([300., 270.])

**Actividad.**

Mónica hace aretes y cadenitas de joyería. Es tan buena, que todo lo que hace lo vende.

Le toma 30 minutos hacer un par de aretes y una hora hacer una cadenita, y como Mónica también es estudihambre, solo dispone de 10 horas a la semana para hacer las joyas. Por otra parte, el material que compra solo le alcanza para hacer 15 unidades (el par de aretes cuenta como unidad) de joyas por semana.

La utilidad que le deja la venta de las joyas es 
 15 en cada par de aretes y 
20 en cada cadenita.

¿Cuántos pares de aretes y cuántas cadenitas debería hacer Mónica para maximizar su utilidad?

1. Identificar criterio
   * Maximizar las ganacias de la utilidad. 
2. Variables de control
   * Cantidad de Aretes que hace (A)
   * Cantidad de Cadenas que hace (C)

3. Función de costo
   * Costo(A, C)= 15A + 20C
4. Información adicional (restricciones)
   * Hace unos aretes en 0.5 hora
   * Hace una cadena en 1 hora
   * Solo cuenta con 10 horas semanales
   * 15 unidades semanales
  
   * 0.5A + 1C $\leq $ 10
   * A + C $\leq $ 15

$$ \min_{A, C} -15A -20C $$
$$ \text {s.t.} $$
$$ 0.5A+1C≤10 $$
$$ A+C ≤ 15 $$

In [209]:
import numpy as np
import scipy.optimize as opt

c=np.array([
    -15,
    -20
])

Aub=np.array([
    [0.5,  1],
    [  1,  1]
])

bub=np.array([
    10,
    15
])

sol3= opt.linprog(c,Aub,bub,integrality=1) # Este comando ya da la respuesta para la forma vector
sol3.fun

-250.0

In [211]:
sol3.x

array([10.,  5.])

In [213]:
Aub@sol3.x

array([10., 15.])

**4. Problema de transporte 1**

Una  empresa tiene dos fábricas A y B.  En ellas  se fabrica un determinado  producto, a razón de 500  y 400 unidades por día respectivamente.  El producto  ha  de  ser distribuido posteriormente  a  tres  centros  C,  D  y  E,  que  requieren,  respectivamente,  200,  300  y  400  unidades.  Los  costos  de  transportar cada unidad del producto desde cada fábrica a cada centro distribuidor son los  indicados  en la tabla  siguiente: 

Factoría|C|D|E|Fabricación (Unidades)
:----|----|----|----|----
A|  50 u.m|60 u.m|10 u.m|500 u
B|  25 u.m|40 u.m|20 u.m|400 u
Demanda|200|300|400|

**¿De qué manera  deben  organizar  el transporte a fin de que los gastos sean mínimos?**

1. Identificar criterio
   * Minimizar gastos de transporte
2. Variables de control
   * Cantidad de producto de A para el centro C (AC)
   * Cantidad de producto de A para el centro D (AD)
   * Cantidad de producto de A para el centro E (AE)
   * Cantidad de producto de B para el centro C (BC)
   * Cantidad de producto de B para el centro D (BD)
   * Cantidad de producto de B para el centro E (BE)

3. Función de costo
   * Costo(AC,AD,AE,BC,BD,BE)= 50AC+60AD+10AE+25BC+40BD+20BE
4. Información adicional (restricciones)
   *  50AC+60AD+10AE $\leq$ 500u
   *  25BC+40BD+20BE $\leq$ 400u
   *  50AC+25BC $\leq$ 200u
   *  60AD+40BD $\leq$ 300u
   *  10AE+20BE $\leq$ 400u

$$ \min_{AC,AD,AE,BC,BD,BE} 50AC+60AD+10AE+25BC+40BD+20BE $$
$$ \text {s.t.} $$
$$ AC+AD+AE \leq 500u $$
$$ BC+BD+BE \leq 400u $$
$$ AC+BC \geq 200u $$
$$ AD+BD \geq 300u $$
$$ AE+BE \geq 400u $$

In [2]:
import numpy as np
import scipy.optimize as opt

c=np.array([
    50,
    60,
    10,
    25,
    40,
    20
])

Aub=np.array([
    [  1,  1,  1,  0,  0,  0],
    [  0,  0,  0,  1,  1,  1],
    [ -1,  0,  0, -1,  0,  0],
    [  0, -1,  0,  0, -1,  0],
    [  0,  0, -1,  0,  0, -1]
])

bub=np.array([
    500,
    400,
    -200,
    -300,
    -400
])

sol4= opt.linprog(c,Aub,bub) # Este comando ya da la respuesta para la forma vector
sol4.fun

23000.0

In [4]:
sol4.x

array([  0., 100., 400., 200., 200.,   0.])

In [6]:
Aub@sol4.x

array([ 500.,  400., -200., -300., -400.])

**Optimización de inversión en bonos**

El objetivo de este problema es determinar la mejor estrategia de inversión, dados diferentes tipos de bono, la máxima cantidad que puede ser invertida en cada bono, el porcentaje de retorno y los años de madurez. También hay una cantidad fija de dinero disponible ($\$750,000$). Por lo menos la mitad de este dinero debe ser invertido en bonos con 10 años o más para la madurez. Se puede invertir un máximo del $25\%$ de esta cantidad en cada bono. Finalmente, hay otra restricción que no permite usar más de $35\%$ en bonos de alto riesgo.

Existen seis (6) opciones de inversión con las letras correspondientes $A_i$

1. $A_1$:(Tasa de retorno=$8.65\%$; Años para la madurez=11, Riesgo=Bajo)
1. $A_2$:(Tasa de retorno=$9.50\%$; Años para la madurez=10, Riesgo=Alto)
1. $A_3$:(Tasa de retorno=$10.00\%$; Años para la madurez=6, Riesgo=Alto)
1. $A_4$:(Tasa de retorno=$8.75\%$; Años para la madurez=10, Riesgo=Bajo)
1. $A_5$:(Tasa de retorno=$9.25\%$; Años para la madurez=7, Riesgo=Alto)
1. $A_6$:(Tasa de retorno=$9.00\%$; Años para la madurez=13, Riesgo=Bajo)

Lo que se quiere entonces es maximizar el retorno que deja la inversión.

Este problema puede ser resuelto con programación lineal. Formalmente, puede ser descrito como:

$$\max_{A_1,A_2,...,A_6}\sum^{6}_{i=1} A_iR_i,$$

donde $A_i$ representa la cantidad invertida en la opción, y $R_i$ representa la tasa de retorno respectiva.

1. Identificar criterio
   * Maximizar el retorno que deja la inversión
2. Variables de control
   * Cantidad inverida de A1 (A1)
   * Cantidad inverida de A2 (A2)
   * Cantidad inverida de A3 (A3)
   * Cantidad inverida de A4 (A4)
   * Cantidad inverida de A5 (A5)
   * Cantidad inverida de A6 (A6)

3. Función de costo
   * Costo(A1,A2,A3,A4,A5,A6)= 0.865 A1 + 0.95 A2 +0.10 A3 + 0.875 A4 + 0.925 A5 +0.90 A6
4. Información adicional (restricciones)
   * A1+A2+A3+A4+A5+A6 $\leq $ 750000
   * A1+A2+A4+A6 $\geq $ 375000
   * A2+A3+A5 $\leq $ 262500
   * Bonos $\leq $ 187500

$$ \min_{A1,A2,A3,A4,A5,A6} -0.865 A1 - 0.95 A2 - 0.10 A3 - 0.875 A4 - 0.925 A5 - 0.90 A6 $$
$$ \text {s.t.} $$
$$ A1+A2+A3+A4+A5+A6 \leq  750000 $$
$$ A1+A2+A4+A6 \geq  375000 $$
$$ A2+A3+A5 \leq  262500 $$
$$ A1 \leq  187500 $$
$$ A2 \leq  187500 $$
$$ A3 \leq  187500 $$
$$ A4 \leq  187500 $$
$$ A5 \leq  187500 $$
$$ A6 \leq  187500 $$

In [220]:
import numpy as np
import scipy.optimize as opt

c=np.array([
    -0.865,
    -0.950,
    -0.100,
    -0.875,
    -0.925,
    -0.900
])

Aub=np.array([
    [ 1, 1, 1, 1, 1, 1],
    [-1,-1, 0,-1, 0,-1],
    [ 0, 1, 1, 0, 1, 0],
    [ 1, 0, 0, 0, 0, 0],
    [ 0, 1, 0, 0, 0, 0],
    [ 0, 0, 1, 0, 0, 0],
    [ 0, 0, 0, 1, 0, 0],
    [ 0, 0, 0, 0, 1, 0],
    [ 0, 0, 0, 0, 0, 1]
])

bub=np.array([
    750000,
    -375000,
    262500,
    187500,
    187500,
    187500,
    187500,
    187500,
    187500
])

sol5= opt.linprog(c,Aub,bub,integrality=1) # Este comando ya da la respuesta para la forma vector
sol5.fun

-677625.0

In [222]:
sol5.x

array([112500., 187500.,      0., 187500.,  75000., 187500.])

In [224]:
Aub@sol5.x

array([ 750000., -675000.,  262500.,  112500.,  187500.,       0.,
        187500.,   75000.,  187500.])

### A05 - Programación lineal

**Ejercicio 1**

Se quiere producir comida para gatos de la manera más barata, no obstante se debe también asegurar que se cumplan los datos requeridos de analisis nutricional. Por lo que se quiere variar la cantidad de cada ingrediente para cumplir con los estandares nutricionales. Los requisitos que se tienen es que en 100 gramos, se deben tener por lo menos 9 gramos de proteína y  7 gramos de grasa. Así mismo, no se debe tener más de 2.5 gramos de fibra y 0.5 gramos de sal.

1. Identificar criterio
   * Minimizar los gastos para la producción de la comida de gatos
2. Variables de control
   * Cantidad de Pollo (p)
   * Cantidad de Carne (ca)
   * Cantidad de Cordero (co)
   * Cantidad de Arroz (a)
   * Cantidad de Trigo (t)
   * Cantidad de Gel(g)
3. Función de costo
   * Costo(p,ca,co,a,t,g)= 0.012p+0.009ca+0.010co+0.003a+0.005t+0.002g
4. Información adicional (restricciones)
   * Gramos totales = 100g
 
   * $ Proteína \geq 9g $
     
$ 0.10p+0.20ca+0.15co+0.04t \geq 9g $
     
   * $ Grasa \geq 7g $

$ 0.08p+0.10ca+0.11co+0.01a+0.01t  \geq 7g $

   * $ Fibra \leq 2.5g $

$ 0.001p+0.005ca+0.005co+0.10a+0.15t  \leq 2.5g $

   * $ Sal \leq 0.5 $

$ 0.002p+0.005ca+0.007co+0.002a+0.008t \leq 0.5g $

$$ \min_{p,ca,co,a,t,g} 0.012p+0.009ca+0.010co+0.003a+0.005t+0.002g $$
$$ \text {s.t.} $$
$$ p+ca+co+a+t+g = 100 $$
$$ 0.10p+0.20ca+0.15co+0.04t \geq 9g $$
$$ 0.08p+0.10ca+0.11co+0.01a+0.01t  \geq 7g $$
$$ 0.001p+0.005ca+0.005co+0.10a+0.15t  \leq 2.5g $$
$$ 0.002p+0.005ca+0.007co+0.002a+0.008t \leq 0.5g $$

In [175]:
import numpy as np
import scipy.optimize as opt

c=np.array([
    0.012,
    0.009,
    0.010,
    0.003,
    0.005,
    0.002
])

Aub=np.array([
    [-0.10,-0.20,-0.15,    0,-0.04,   0],
    [-0.08,-0.10,-0.11,-0.01,-0.01,   0],
    [0.001,0.005,0.005, 0.10, 0.15,   0],
    [0.002,0.005,0.007,0.002,0.008,   0],
])

bub=np.array([
    -9,
    -7,
    2.5,
    0.5
])

Aeq= np.array([
    [1,1,1,1,1,1]
])

beq=np.array([
    100
])

sol6= opt.linprog(c,Aub,bub,Aeq,beq) # Este comando ya da la respuesta para la forma vector
sol6.fun

0.69

In [177]:
sol6.x

array([ 0., 70.,  0.,  0.,  0., 30.])

In [179]:
Aub@sol6.x

array([-14.  ,  -7.  ,   0.35,   0.35])

**Ejercicio 2**

La Comisión Federal de Electricidad (CFE) dispone de cuatro plantas de generación para satisfacer la demanda diaria eléctrica en cuatro ciudades, Guadalajara, León y Morelia. Las plantas 1, 2 y 3 pueden satisfacer 75, 50 y 60 millones de kW al día respectivamente. Las necesidades de las ciudades de Guadalajara, León y Morelia son de 60, 45 y 60 millones de Kw al día respectivamente.

Los costos asociados al envío de suministro energético por cada millón de kW entre cada planta y cada ciudad son los registrados en la siguiente tabla.

1. Identificar criterio
   * Minimizar los costos de logísticas. 
2. Variables de control
   * Cantidad de energia de planta 1 a Guadalajara (pg)
   * Cantidad de energia de planta 1 a León (pl)
   * Cantidad de energia de planta 1 a Morelia (pm)
   * Cantidad de energia de planta 2 a Guadalajara (sg)
   * Cantidad de energia de planta 2 a León (sl)
   * Cantidad de energia de planta 2 a Morelia (sm)
   * Cantidad de energia de planta 3 a Guadalajara (tg)
   * Cantidad de energia de planta 3 a León (tl)
   * Cantidad de energia de planta 3 a Morelia (tm)

3. Función de costo
   * Costo(pg,pl,pm,sg,sl,sm,tg,tl,tm)= 5pg+2pl+7pm+3sg+4sl+5sm+5tg+2tl+3tm
4. Información adicional (restricciones)
   * Planta 1 $\leq$ 75kw
   * Planta 2 $\leq$ 50kw
   * Planta 3 $\leq$ 60kw
   * Guadalajara $\geq$ 60kw
   * León $\geq$ 45kw
   * Morelia $\geq$ 60kw

$$ \min_{pg,pl,pm,sg,sl,sm,tg,tl,tm} 5pg+2pl+7pm+3sg+4sl+5sm+5tg+2tl+3tm $$
$$ \text {s.t.} $$
$$ pg+sg+tg \geq 60kw $$
$$ pl+sl+tl \geq 45kw $$
$$ pm+sm+tm \geq 60kw $$

$$ pg+pl+pm \leq 75kw $$
$$ sg+sl+sm \leq 50kw $$
$$ tg+tl+tm \leq 60kw $$

In [181]:
import numpy as np
import scipy.optimize as opt

c=np.array([
    5,
    2,
    7,
    3,
    4,
    5,
    5,
    2,
    3
])

Aub=np.array([
    [-1, 0, 0,-1, 0, 0,-1, 0, 0],
    [ 0,-1, 0, 0,-1, 0, 0,-1, 0],
    [ 0, 0,-1, 0, 0,-1, 0, 0,-1],
    [ 1, 1, 1, 0, 0, 0, 0, 0, 0],
    [ 0, 0, 0, 1, 1, 1, 0, 0, 0],
    [ 0, 0, 0, 0, 0, 0, 1, 1, 1]
])

bub=np.array([
    -60,
    -45,
    -60,
     75,
     50,
     60
])

sol7= opt.linprog(c,Aub,bub,integrality=1) # Este comando ya da la respuesta para la forma vector
sol7.fun

470.0

In [183]:
sol7.x

array([10., 45.,  0., 50.,  0.,  0.,  0.,  0., 60.])

In [185]:
Aub@sol7.x

array([-60., -45., -60.,  55.,  50.,  60.])

### A06_Programación lineal

**Ejercicio 1.**

Una carpintería local fabrica sillas, mesas, libreros y bases de cama. Hay dos empleados en esta carpintería: un empleado experimentado y un aprendiz. El aprendiz tarda aproximadamente 50% más tiempo que el carpintero experimentado en construir cualquier cosa, además de que tiene un desperdicio de alrededor de 20% de material. Los materiales y tiempos necesarios para construir algo se desglozan en la siguiente tabla:

Las mesas se venden en $9000, las sillas en $3000, los libreros en $10000, y las bases de cama en $9000. Suponiendo una jornada de 40 horas a la semana y que tienen 100 unidades de madera.

1. Identificar criterio
   * Maximizar las ganancias de la semana
     
2. Variables de control
   * Cantidad de sillas que hace el experimentado (se)
   * Cantidad de mesas que hace el experimentado (me)
   * Cantidad de libreros que hace el experimentado (le)
   * Cantidad de bases que hace el experimentado (be)
   * Cantidad de sillas que hace el aprendiz (sa)
   * Cantidad de mesas que hace el aprendiz (ma)
   * Cantidad de libreros que hace el aprendiz (la)
   * Cantidad de bases que hace el aprendiz (ba)
     
3. Función de costo
   * Costo(se,me,le,be,sa,ma,la,ba)= 9000me+9000ma+3000se+3000sa+10000le+10000la+9000be+9000ba
     
4. Información adicional (restricciones)
   
   * Tiempo $\leq$ 40 cada quien
   
 3me+1se+4le+3be $\leq$ 40

 4.5ma+1.5sa+6la+4.5ba $\leq$ 40

* Material $\leq$ 100

6me+7.2ma+2se+2.4sa+5le+6la+5be+6ba $\leq$ 100

$$ \min_{me,ma,se,sa,le,la,be,ba} -9000me-9000ma-3000se-3000sa-10000le-10000la-9000be-9000ba $$
$$ \text {s.t.} $$
$$3me+1se+4le+3be \leq 40$$
$$4.5ma+1.5sa+6la+4.5ba \leq 40$$
$$6me+7.2ma+2se+2.4sa+5le+6la+5be+6ba \leq 100$$

In [187]:
import numpy as np
import scipy.optimize as opt

c=np.array([
    -9000,
    -9000,
    -3000,
    -3000,
    -10000,
    -10000,
    -9000,
    -9000
])

Aub=np.array([
    [   3,   0,   1,   0,   4,   0,   3,   0],
    [   0, 4.5,   0, 1.5,   0,   6,   0, 4.5],
    [   6, 7.2,   2, 2.4,   5,   6,   5,   6]
])

bub=np.array([
    40,
    40,
    100
])

sol8= opt.linprog(c,Aub,bub,integrality=1) # Este comando ya da la respuesta para la forma vector
sol8.fun

-176000.0

In [189]:
sol8.x

array([ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00, -9.47390314e-15,
        9.00000000e+00,  2.00000000e+00,  1.00000000e+00,  6.00000000e+00])

In [195]:
Aub@sol8.x

array([ 40.,  39., 100.])